name: 'Setup Tailscale SSH'
description: 'Wait for Tailscale network readiness, configure SSH, and validate connections to target machines'

inputs:
  machine-names:
    description: 'Comma-separated list of Tailscale machine names to validate'
    required: true
  ssh-user:
    description: 'SSH username for connection validation'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Wait for Tailscale Network Readiness
      shell: bash
      run: |
        echo "Waiting for Tailscale network to be ready..."
        max_wait=60
        elapsed=0

        while [ $elapsed -lt $max_wait ]; do
          if tailscale status --json | jq -e '.BackendState == "Running"' > /dev/null 2>&1; then
            echo "Tailscale network is ready"
            break
          fi
          sleep 2
          elapsed=$((elapsed + 2))
        done

        if [ $elapsed -ge $max_wait ]; then
          echo "Tailscale network not ready after ${max_wait}s"
          exit 1
        fi

    - name: Configure SSH & Validate Connections
      shell: bash
      env:
        SSH_USER: ${{ inputs.ssh-user }}
        MACHINE_NAMES: ${{ inputs.machine-names }}
      run: |
        mkdir -p ~/.ssh
        echo "Host *
          UserKnownHostsFile=/dev/null
          StrictHostKeyChecking no" > ~/.ssh/config
        chmod 644 ~/.ssh/config

        validate_connection() {
          local machine_name=$1
          local max_retries=3
          local retry_delay=5

          for attempt in $(seq 1 $max_retries); do
            echo "Connection attempt $attempt/$max_retries to $machine_name"

            if ! tailscale status | grep -q "$machine_name"; then
              echo "Machine $machine_name not found in Tailscale network"
              if [ $attempt -eq $max_retries ]; then
                return 1
              fi
              sleep $retry_delay
              continue
            fi

            MACHINE_IP=$(tailscale ip -4 $machine_name)
            if ssh -o ConnectTimeout=10 -o BatchMode=yes $SSH_USER@$MACHINE_IP "echo 'Connection test'" > /dev/null 2>&1; then
              echo "Successfully validated connection to $machine_name"
              return 0
            fi

            echo "SSH validation failed for $machine_name"
            if [ $attempt -lt $max_retries ]; then
              sleep $retry_delay
            fi
          done

          echo "Failed to establish connection to $machine_name after $max_retries attempts"
          return 1
        }

        IFS=',' read -ra MACHINES <<< "$MACHINE_NAMES"
        for machine in "${MACHINES[@]}"; do
          machine=$(echo "$machine" | xargs)
          echo -e "\nLOG:Validating connection to $machine..."
          if ! validate_connection "$machine"; then
            echo "Error: Failed to establish reliable connection to $machine"
            exit 1
          fi
        done
        echo "All machine connections validated successfully"
